name: Linear PR Title
description: Update your PR's title to the linked Linear issue's title
branding:
  icon: copy
  color: yellow
inputs:
  linear-api-key:
    description: Linear personal API key
    required: true
  github-token:
    description: GitHub API auth
    required: true
  placeholder:
    description: The exact title placeholder that should be replaced
    required: false
  include-prefix:
    description: Whether to include a conventional commit prefix (e.g. `fix:`)
    required: false
  include-project:
    description: Whether to include the project's name
    required: false
  include-parent:
    description: Whether to include the parent's title
    required: false
runs:
  using: "node20"
  main: "dist/index.js"
